config/routes.rb
Rails.application.routes.draw do
  get 'photos/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens
  resources :photos, only: [:index] 
  # Defines the root path route ("/")
  root "photos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	validates :name, presence: true, length: { maximum: 20 }
	validates_inclusion_of :age, in: 1..30, message: 'has to be valid'
	validates_inclusion_of :softness, in: 1..10, message: 'has to have a valid index'
	validates_inclusion_of :cuteness, in: 1..10, message: 'has to have a valid index'
end

app/models/photo.rb
require 'flickr'

class Photo < ApplicationRecord
  def self.fetch(user_id)
  	key = ENV['FLICKR_API_KEY']
  	secret = ENV['FLICKR_SECRET']
  	flickr = Flickr.new(key, secret)

    begin
      flickr.photos.search(:user_id => user_id)      
    rescue StandardError => e
      nil
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    format_data_as_requested(@kittens)
  end

  def create
    @kitten = Kitten.new(kitten_params) 
    if @kitten.save
      flash[:notice] = "Your kitten was added to the database"
      redirect_to kitten_path(@kitten)
    else
      flash[:notice] = "Something went wrong"
      render :new, status: :unprocessable_entity
    end                             
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @kitten = Kitten.new
  end

  def show
    @kitten = Kitten.find(params[:id])
    format_data_as_requested(@kitten)
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :softness, :cuteness)
  end

  def format_data_as_requested(object)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => object }
      format.json { render :json => object }
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    if params[:flickr_info]
      @flickr_info = params_user_id
      @photos_list = Photo.fetch(@flickr_info[:user_id])
      if @photos_list
        render "index"
      else
        flash.now[:notice] = "Enter valid user_id" 
        render "index"
      end
    end
  end

  private

  def params_user_id
    params.require(:flickr_info).permit(:user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/kittens/_form.html.erb
<% if @kitten.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @kitten.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

 <%= form_with model: @kitten, url: kittens_path do |form| %>
 <p><%= form.label :softness %><br>
 <%= form.text_field :softness, placeholder: "On a scale of 10"%></p>

 <p><%= form.submit "Create Entry" %></p>
 <% end %>

app/views/kittens/edit.html.erb
<h2>Edit Your Kitten</h2>

<% if @kitten.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @kitten.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model:@kitten, url: kitten_path(@kitten), method: :patch do |form| %>
	<p>
	<%= form.label :name %><br>	
	<%= form.text_field :name %>
	</p>

	<p><%= form.label :age %><br>
	<%= form.text_field :age %></p>

	<p><%= form.label :cuteness %><br>
	<%= form.text_field :cuteness,\
	 placeholder: "On a scale of 10" %></p>

	<p><%= form.label :softness %><br>
	<%= form.text_field :softness,\
	 placeholder: "On a scale of 10" %></p>

	<p><%= form.submit "Update" %></p>
<% end %>

app/views/kittens/index.html.erb
<h1>Kittens hub</h1>

<%= link_to "New Kitten", new_kitten_path %>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten_path(kitten) %>
    </li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h2>New Kitten</h2>

<%= render "form" %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>

<p>Age: <%= @kitten.age %></p>
<p>Softness: <%= @kitten.softness %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>

<%= link_to "Home", kittens_path %>
<%= link_to "Edit", edit_kitten_path(@kitten) %>
<%= link_to "Destroy", kitten_path(@kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/index.html.erb
<% unless @photos_list %>
<h3><%= flash.now[:notice] %></h3>
<h2>Search flickr photos by id</h2>
	<%= form_with scope: :flickr_info, url: photos_index_path, method: :get do |form| %>
		<p><%= form.label :user_id, "User ID" %><br>
		<%= form.text_field :user_id %></p>

		<p><%= form.submit "Fetch Images" %></p>
	<% end %>
<% else %>
	<%= link_to "Home", photos_index_path %><br>
	<% @photos_list.each do |photo| %>
		<% photo_id = photo["id"] %>
		<% server_id = photo["server"] %>
		<% secret_id = photo["secret"] %>
		<%= image_tag("https://live.staticflickr.com/#{server_id}/#{photo_id}_#{secret_id}.jpg") %>
	<% end %>
<% end %>